### ISSUE TITLE
As any type of user, I want to login and sign out of the app

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/feelit-chips-frontend#37]
- [x] Create login page #38
- [x] Add sign-out button to header #39  
- [x] Check user is valid on protected pages and display their name #40
